services:

  terraform:
    image: hashicorp/terraform:${TF_VERSION}
    volumes:
      - ~/.aws:/root/.aws
      - .:/app
    working_dir: /app

  terraform-docs:
    image: cytopia/terraform-docs
    volumes:
      - .:/app
    working_dir: /app
