version: '3.7'
services:

  terraform:
    image: hashicorp/terraform:1.2.4
    volumes:
      - '~/.aws:/root/.aws'
      - '.:/app'
    working_dir: '/app'

  terraform-docs:
    image: cytopia/terraform-docs
    volumes:
      - '.:/app'
    working_dir: '/app'
