version: '3.7'
services:

  terraform:
    image: hashicorp/terraform:${TF_VERSION}
    volumes:
      - '~/.aws:/root/.aws'
      - '.:/app'
    working_dir: '/app'

  terraform-docs:
    image: cytopia/terraform-docs:0.13.0
    volumes:
      - '.:/app'
    working_dir: '/app'
